"""
ROUTES ANALYTICS PACKAGE
========================
Modularized analytics router package containing market intelligence,
simulations, strategy tracking, and background market scanners.
"""

from core import Heimdall, MarketPredictor, MonteCarlo, RagnarokSimulator, TimeUtils
from core.analyzers import (
    ExecutionWatchdog,
    Helheim,
    Midgard,
    MomentumBreakoutScanner,
    SandboxRegistry,
    SentimentCrawler,
    Svartalfheim,
    Vanaheim,
)
from core.market import SectorRotation, SmartMoneyTracker
from core.price_action.backtest import run_price_action_backtest
from core.price_action.catalog import get_price_action_strategy
from core.settings import settings
from core.simulation import StressTest
from database import Position, Trade, db
from routes.shared import (
    ARBITRAGE_CACHE,
    NEWS_CACHE,
    ORACLE_CACHE,
    SECTOR_CACHE,
    STRATEGY_CACHE,
    SYSTEM_STATE,
    TRAP_CACHE,
    WHALE_CACHE,
    get_system_state_snapshot,
    limiter,
)

from routes.analytics.models import (
    StressTestRequest,
    PredictionRequest,
    MonteCarloRequest,
    RagnarokRequest,
    SimulationBacktestRequest,
    ArbitrageExecutionRequest,
)

from routes.analytics.cache import (
    NEWS_CACHE_FILE,
    _cache_ttl_seconds,
    _current_data_version,
    _cache_is_fresh,
    _mark_cache_timestamp,
    _cache_age_seconds,
    _normalize_arbitrage_universe,
    _arbitrage_cache_bucket,
    _disk_grace_ttl_seconds,
    _persist_news_cache_to_disk,
    _load_news_cache_from_disk,
)

from routes.analytics.market_intel import (
    get_market_news,
    get_sector_map,
    get_market_traps,
    get_prediction,
    get_whales,
    get_smart_money,
    get_seasonality,
    get_market_seasonality,
    get_rrg,
)

from routes.analytics.simulations import (
    run_stress_test_api,
    get_arbitrage,
    execute_arbitrage,
    run_monte_carlo_sim,
    run_ragnarok,
    run_simulation_backtest,
)

from routes.analytics.strategies import (
    get_strategy_proposal,
    get_health,
    get_audit,
    get_watcher_status,
    get_strategy_metrics,
)

from routes.analytics.scanner import (
    ANALYTICS_CACHE_FILE,
    ANALYTICS_LOCK,
    ANALYTICS_CACHE_STATE,
    _safe_int,
    _resolve_analytics_workers,
    _analytics_state_snapshot,
    _analytics_rows_from_state,
    _load_analytics_cache_from_disk,
    _persist_analytics_cache_to_disk,
    get_cached_analytics_rows,
    ensure_analytics_rows,
    _parse_date_prefix,
    _history_last_data_day,
    _parse_analytics_timestamp,
    _analytics_cache_age_seconds,
    _analytics_cache_needs_refresh,
    _analytics_refresh_should_block_response,
    _begin_analytics_scan,
    _update_scan_progress,
    run_analytics_task_logic,
    get_analytics_data,
    get_analytics_status,
    refresh_analytics,
)

from routes.analytics.router import public_router, router

__all__ = [
    "public_router",
    "router",
    "TimeUtils",
    "settings",
    "SYSTEM_STATE",
    "get_system_state_snapshot",
    "SentimentCrawler",
    "SectorRotation",
    "StressTest",
    "Svartalfheim",
    "MarketPredictor",
    "ExecutionWatchdog",
    "Heimdall",
    "Vanaheim",
    "SandboxRegistry",
    "Helheim",
    "Midgard",
    "SmartMoneyTracker",
    "MonteCarlo",
    "RagnarokSimulator",
    "MomentumBreakoutScanner",
    "run_price_action_backtest",
    "get_price_action_strategy",
    "Trade",
    "Position",
    "db",
    "limiter",
    "NEWS_CACHE",
    "SECTOR_CACHE",
    "TRAP_CACHE",
    "ORACLE_CACHE",
    "STRATEGY_CACHE",
    "WHALE_CACHE",
    "ARBITRAGE_CACHE",
    "StressTestRequest",
    "PredictionRequest",
    "MonteCarloRequest",
    "RagnarokRequest",
    "SimulationBacktestRequest",
    "ArbitrageExecutionRequest",
    "NEWS_CACHE_FILE",
    "_cache_ttl_seconds",
    "_current_data_version",
    "_cache_is_fresh",
    "_mark_cache_timestamp",
    "_cache_age_seconds",
    "_normalize_arbitrage_universe",
    "_arbitrage_cache_bucket",
    "_disk_grace_ttl_seconds",
    "_persist_news_cache_to_disk",
    "_load_news_cache_from_disk",
    "get_market_news",
    "get_sector_map",
    "get_market_traps",
    "get_prediction",
    "get_whales",
    "get_smart_money",
    "get_seasonality",
    "get_market_seasonality",
    "get_rrg",
    "run_stress_test_api",
    "get_arbitrage",
    "execute_arbitrage",
    "run_monte_carlo_sim",
    "run_ragnarok",
    "run_simulation_backtest",
    "get_strategy_proposal",
    "get_health",
    "get_audit",
    "get_watcher_status",
    "get_strategy_metrics",
    "ANALYTICS_CACHE_FILE",
    "ANALYTICS_LOCK",
    "ANALYTICS_CACHE_STATE",
    "_safe_int",
    "_resolve_analytics_workers",
    "_analytics_state_snapshot",
    "_analytics_rows_from_state",
    "_load_analytics_cache_from_disk",
    "_persist_analytics_cache_to_disk",
    "get_cached_analytics_rows",
    "ensure_analytics_rows",
    "_parse_date_prefix",
    "_history_last_data_day",
    "_parse_analytics_timestamp",
    "_analytics_cache_age_seconds",
    "_analytics_cache_needs_refresh",
    "_analytics_refresh_should_block_response",
    "_begin_analytics_scan",
    "_update_scan_progress",
    "run_analytics_task_logic",
    "get_analytics_data",
    "get_analytics_status",
    "refresh_analytics",
]
