import datetime
import os
from core.settings import settings


def generate_portfolio_html_summary(report_data):
    """
    Generates a professional HTML summary (suitable for PDF conversion or email).
    """
    p = report_data.get("portfolio", {})
    s = report_data.get("summary", {})
    risk = report_data.get("risk", {})
    positions = report_data.get("positions", [])

    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; margin: 40px; background-color: #f8f9fa; }}
            .container {{ max-width: 900px; margin: auto; background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }}
            h1 {{ color: #1a5f7a; border-bottom: 3px solid #d4af37; padding-bottom: 15px; margin-top: 0; }}
            .summary-grid {{ display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin-bottom: 30px; }}
            .summary-card {{ background: #f1f3f5; padding: 15px; border-radius: 8px; border-left: 4px solid #1a5f7a; }}
            .summary-card h3 {{ margin: 0; font-size: 0.9em; color: #666; text-transform: uppercase; }}
            .summary-card p {{ margin: 10px 0 0; font-size: 1.4em; font-weight: bold; color: #1a5f7a; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 0.95em; }}
            th, td {{ border-bottom: 1px solid #eee; padding: 12px; text-align: left; }}
            th {{ background-color: #f1f3f5; color: #1a5f7a; font-weight: bold; }}
            .pnl-pos {{ color: #28a745; }}
            .pnl-neg {{ color: #dc3545; }}
            .badge {{ padding: 4px 8px; border-radius: 4px; font-size: 0.85em; font-weight: bold; }}
            .badge-gold {{ background: #fff3cd; color: #856404; border: 1px solid #ffeeba; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Portfolio Statement: {p.get('name', 'N/A')}</h1>
            
            <div class="summary-grid">
                <div class="summary-card">
                    <h3>Market Value</h3>
                    <p>{s.get('market_value', 0):,.2f} EGP</p>
                </div>
                <div class="summary-card">
                    <h3>Unrealized P&L</h3>
                    <p class="{'pnl-pos' if s.get('unrealized_pnl',0) >= 0 else 'pnl-neg'}">
                        {s.get('unrealized_pnl', 0):+,.2f} ({s.get('unrealized_pnl_pct', 0):+.2f}%)
                    </p>
                </div>
                <div class="summary-card">
                    <h3>Risk Health</h3>
                    <p>{risk.get('health_score', 0)} / 100</p>
                </div>
                <div class="summary-card">
                    <h3>Open Positions</h3>
                    <p>{s.get('open_positions', 0)}</p>
                </div>
            </div>
            
            <h2>Open Positions Overview</h2>
            <table>
                <thead>
                    <tr>
                        <th>Ticker</th>
                        <th>Shares</th>
                        <th>Entry</th>
                        <th>Last</th>
                        <th>P&L %</th>
                        <th>Action Status</th>
                    </tr>
                </thead>
                <tbody>
    """

    for pos in positions:
        pnl_class = "pnl-pos" if pos.get("unrealized_pnl_pct", 0) >= 0 else "pnl-neg"
        badge_class = "badge-gold" if pos.get("action") != "HOLD_MONITOR" else ""
        html += f"""
                    <tr>
                        <td><strong>{pos['ticker']}</strong></td>
                        <td>{pos['shares']}</td>
                        <td>{pos['entry_price']:.2f}</td>
                        <td>{pos['current_price']:.2f}</td>
                        <td class="{pnl_class}">{pos['unrealized_pnl_pct']:.2f}%</td>
                        <td><span class="badge {badge_class}">{pos['action']}</span></td>
                    </tr>
        """

    html += f"""
                </tbody>
            </table>
            
            <div style="margin-top: 40px; border-top: 1px solid #ddd; padding-top: 20px; color: #999; font-size: 0.8em; text-align: center;">
                Generated by Horus Analytics | {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
            </div>
        </div>
    </body>
    </html>
    """
    return html


def save_report_to_disk(content, filename, mode="w"):
    """
    Saves generated content to the centralized reports directory.
    """
    reports_dir = settings.REPORTS_DIR
    os.makedirs(reports_dir, exist_ok=True)
    file_path = os.path.join(reports_dir, filename)

    if mode == "wb":
        with open(file_path, "wb") as f:
            f.write(content.getvalue() if hasattr(content, "getvalue") else content)
    else:
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)

    return file_path
