import {
    LayoutDashboard,
    Radar,
    Send,
    Zap,
    Brain,
    Waves,
    Target,
    Repeat,
    GanttChart,
    Cpu,
    Globe,
    CalendarDays,
    BarChart3,
    FileText,
    History,
    Coins,
    Users,
    Settings,
} from 'lucide-react';

export const ROUTES = [
    {
        label: 'nav.dashboard',
        shortLabel: 'HOME',
        icon: LayoutDashboard,
        href: '/',
        color: "text-sky-500",
        hoverColor: "group-hover:text-sky-500",
        priority: 'anchor',
    },
    {
        label: 'nav.telegram',
        shortLabel: 'RAIL',
        icon: Send,
        href: '/telegram',
        color: "text-amber-300",
        hoverColor: "group-hover:text-amber-300",
        priority: 'anchor',
    },
    {
        label: 'nav.scanner',
        shortLabel: 'SCAN',
        icon: Radar,
        href: '/scanner',
        color: "text-violet-500",
        hoverColor: "group-hover:text-violet-500",
        priority: 'feeder',
    },
    {
        label: 'nav.live',
        shortLabel: 'LIVE',
        icon: Zap,
        href: '/live',
        color: "text-orange-700",
        hoverColor: "group-hover:text-orange-700",
    },
    {
        label: 'nav.oracle',
        shortLabel: 'ORCL',
        icon: Brain,
        href: '/oracle',
        color: "text-cyan-400",
        hoverColor: "group-hover:text-cyan-400",
        priority: 'feeder',
    },
    {
        label: 'nav.whales',
        shortLabel: 'WHAL',
        icon: Waves,
        href: '/whales',
        color: "text-blue-400",
        hoverColor: "group-hover:text-blue-400",
        priority: 'feeder',
    },
    {
        label: 'nav.traps',
        shortLabel: 'TRAP',
        icon: Target,
        href: '/traps',
        color: "text-rose-400",
        hoverColor: "group-hover:text-rose-400",
        priority: 'feeder',
    },
    {
        label: 'nav.arbitrage',
        shortLabel: 'ARB',
        icon: Repeat,
        href: '/arbitrage',
        color: "text-emerald-500",
        hoverColor: "group-hover:text-emerald-500",
    },
    {
        "label": "nav.strategy",
        "shortLabel": "STRAT",
        "icon": GanttChart,
        "href": "/strategy",
        "color": "text-indigo-500",
        "hoverColor": "group-hover:text-indigo-500"
    },
    {
        "label": "nav.optimization",
        "shortLabel": "LAB",
        "icon": Cpu,
        "href": "/optimization",
        "color": "text-cyan-400",
        "hoverColor": "group-hover:text-cyan-400"
    },
    {
        label: 'nav.executionQuality',
        shortLabel: 'AUDIT',
        icon: History,
        href: '/execution-quality',
        color: "text-rose-500",
        hoverColor: "group-hover:text-rose-500",
    },
    {
        "label": "nav.news",
        "shortLabel": "NEWS",
        "icon": Globe,
        "href": "/news",
        "color": "text-slate-400",
        "hoverColor": "group-hover:text-slate-400",
        "priority": "feeder"
    },
    {
        label: 'nav.seasonality',
        shortLabel: 'SEAS',
        icon: CalendarDays,
        href: '/seasonality',
        color: "text-amber-400",
        hoverColor: "group-hover:text-amber-400",
    },
    {
        label: 'nav.sectors',
        shortLabel: 'SECT',
        icon: BarChart3,
        href: '/sectors',
        color: "text-purple-400",
        hoverColor: "group-hover:text-purple-400",
        priority: 'feeder',
    },
    {
        label: 'nav.analytics',
        shortLabel: 'ANLY',
        icon: BarChart3,
        href: '/analytics',
        color: "text-blue-500",
        hoverColor: "group-hover:text-blue-500",
        priority: 'feeder',
    },
    {
        label: 'nav.analysis_report',
        shortLabel: 'RPT',
        icon: FileText,
        href: '/reports/weekly',
        color: "text-indigo-400",
        hoverColor: "group-hover:text-indigo-400",
    },
    {
        label: 'nav.audit_trail',
        shortLabel: 'AUD',
        icon: History,
        href: '/audit',
        color: "text-blue-500",
        hoverColor: "group-hover:text-blue-500",
    },
    {
        label: 'nav.simulation',
        shortLabel: 'SIM',
        icon: Cpu,
        href: '/simulation',
        color: "text-rose-500",
        hoverColor: "group-hover:text-rose-500",
    },
    {
        label: 'nav.portfolio',
        shortLabel: 'PORT',
        icon: Coins,
        href: '/portfolio',
        color: "text-yellow-500",
        hoverColor: "group-hover:text-yellow-500",
    },
    {
        label: 'nav.subscribers',
        shortLabel: 'SUBS',
        icon: Users,
        href: '/subscribers',
        color: "text-amber-300",
        hoverColor: "group-hover:text-amber-300",
    },
    {
        label: 'nav.settings',
        shortLabel: 'CFG',
        icon: Settings,
        href: '/settings',
        color: "text-slate-400",
        hoverColor: "group-hover:text-slate-400",
    },
];

export const TOP_NAV_ANCHORS = ['/', '/telegram'] as const;

export const TOP_NAV_GROUPS = [
    {
        id: 'intelligence',
        label: 'Intelligence',
        routes: ['/scanner', '/oracle', '/whales', '/traps', '/analytics', '/live', '/news', '/sectors', '/seasonality'],
    },
    {
        id: 'oversight',
        label: 'Oversight',
        routes: ['/reports/weekly', '/audit', '/strategy', '/optimization', '/simulation', '/arbitrage', '/execution-quality'],
    },
    {
        id: 'system',
        label: 'System',
        routes: ['/portfolio', '/subscribers', '/settings'],
    },
] as const;

export const PROVIDER_LABELS: Record<string, string> = {
    METASTOCK_DAT: 'MetaStock DAT',
    CSV: 'MetaStock CSV',
    MUBASHER_DB: 'Mubasher DB',
    DIRECTFN: 'DirectFN Feed',
};
