apiVersion: v1
kind: ConfigMap
metadata:
  name: horus-config
data:
  HOST: "0.0.0.0"
  PORT: "8000"
  DEBUG: "false"
  LOCAL_FEED_AUTO_SELECT_ON_STARTUP: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: horus-secrets
type: Opaque
data:
  # Base64 encoded values for production
  SENTRY_DSN: "Y2hhbmdlbWU="
  TELEGRAM_BOT_TOKEN: "Y2hhbmdlbWU="
  TELEGRAM_CHAT_ID: "Y2hhbmdlbWU="
