"""
HISTORICAL BACKFILL PACKAGE
===========================
Day-by-day simulated time travel backfill engine, universe slice cache,
intraday checkpoint generation, signal persistence, and background orchestration.
"""

from .state import (
    BACKFILL_STATE,
    DEFAULT_BACKFILL_SIGNAL_LANES,
    DEFAULT_BACKFILL_UNIVERSE_CHOICE,
    DEFAULT_PROVISIONING_TRADING_DAYS,
    VALID_BACKFILL_SIGNAL_LANES,
    VALID_BACKFILL_UNIVERSE_CHOICES,
    _DB_LOCK_BASE_SLEEP_SECONDS,
    _DB_LOCK_MAX_SLEEP_SECONDS,
    _DB_LOCK_RETRY_ATTEMPTS,
    _DEFAULT_BACKFILL_INTRADAY_INTERVAL_MINS,
    _REAL_DATETIME,
    _available_tickers,
    _backfill_lock,
    _coerce_plain_datetime,
    _get_or_create_provisioning_row,
    _history_window_start_date,
    _is_market_day,
    _is_sqlite_lock_error,
    _market_days_between,
    _normalize_market_signal_payload,
    _persist_provisioning_state,
    _recent_market_days,
    is_backfill_running,
    logger,
    normalize_backfill_signal_lanes,
    normalize_backfill_universe_choice,
    resolve_backfill_market_choice,
)
from .intraday import (
    _apply_intraday_entry_prices,
    _backfill_intraday_interval_minutes,
    _intraday_checkpoints_for_day,
    _normalize_simulation_cutoff_for_universe,
    _parse_market_times_for_day,
    _resolve_intraday_entry_price,
    _store_intraday_checkpoint_snapshot,
    _store_signals_for_day,
    _upsert_intraday_checkpoint_once,
    _upsert_intraday_checkpoint_with_retry,
    _upsert_signal_once,
    _upsert_signal_with_retry,
)
from .orchestrator import (
    resume_provisioning_if_needed,
    run_backfill,
    start_background_backfill,
)

__all__ = [
    # State & Settings
    "logger",
    "_REAL_DATETIME",
    "DEFAULT_PROVISIONING_TRADING_DAYS",
    "DEFAULT_BACKFILL_UNIVERSE_CHOICE",
    "VALID_BACKFILL_UNIVERSE_CHOICES",
    "DEFAULT_BACKFILL_SIGNAL_LANES",
    "VALID_BACKFILL_SIGNAL_LANES",
    "BACKFILL_STATE",
    "_backfill_lock",
    "_DB_LOCK_RETRY_ATTEMPTS",
    "_DB_LOCK_BASE_SLEEP_SECONDS",
    "_DB_LOCK_MAX_SLEEP_SECONDS",
    "_DEFAULT_BACKFILL_INTRADAY_INTERVAL_MINS",
    "is_backfill_running",
    "_coerce_plain_datetime",
    "_get_or_create_provisioning_row",
    "_persist_provisioning_state",
    "_market_days_between",
    "_is_market_day",
    "_recent_market_days",
    "_history_window_start_date",
    "_available_tickers",
    "_normalize_market_signal_payload",
    "normalize_backfill_universe_choice",
    "resolve_backfill_market_choice",
    "normalize_backfill_signal_lanes",
    "_is_sqlite_lock_error",
    # Intraday & Signals
    "_normalize_simulation_cutoff_for_universe",
    "_parse_market_times_for_day",
    "_backfill_intraday_interval_minutes",
    "_intraday_checkpoints_for_day",
    "_store_signals_for_day",
    "_resolve_intraday_entry_price",
    "_apply_intraday_entry_prices",
    "_upsert_signal_once",
    "_upsert_signal_with_retry",
    "_upsert_intraday_checkpoint_once",
    "_upsert_intraday_checkpoint_with_retry",
    "_store_intraday_checkpoint_snapshot",
    # Orchestrator
    "run_backfill",
    "start_background_backfill",
    "resume_provisioning_if_needed",
]
