"""
SCHEDULING — Facade Module
==========================
Provides full backward compatibility for `core.scheduling`.
All functionality has been decomposed into `core.scheduling`.
"""

import os
import datetime
import threading

from core.settings import settings
from core import TimeUtils, DailyScanner, AutoTrader, AlertManager, TelegramBot_Alerts, Heimdall
from core import pipeline as _pipeline
from database import Signal, SignalRun, SignalDelivery, SignalRecommendation

from core.scheduling import *
from core.scheduling import (
    _TRADE_MONITOR_LOCK,
    _USE_LEGACY_EXECUTOR,
    _NO_SIGNAL_NOTICE_LOCK,
    _NO_SIGNAL_NOTICE_KEYS,
    _AI_DAILY_REPORT_LOCK,
    _AI_DAILY_REPORT_PENDING_DATES,
    _AI_DAILY_REPORT_SENT_DATES,
    _DAILY_SIGNAL_LOCK,
    _DAILY_SIGNAL_PENDING_DATES,
    _DAILY_SIGNAL_COMPLETED_DATES,
    _DAILY_SIGNAL_RETRY_COUNTS,
    _PRE_CLOSE_LOCK,
    _PRE_CLOSE_RETRY_COUNTS,
    _PRE_CLOSE_COMPLETED_DATES,
    _DATA_WAITING_NOTICE_LOCK,
    _DATA_WAITING_NOTICE_SENT_DATES,
    _PENDING_ENTRIES_LOCK,
    _PENDING_ENTRIES_EXECUTED_DATES,
    _MORNING_DAILY_SIGNAL_LOCK,
    _MORNING_DAILY_SIGNAL_COMPLETED_DATES,
    _maybe_broadcast_data_waiting_subscriber_notice,
    _get_daily_signal_retry_count,
    _increment_daily_signal_retry_count,
    _get_pre_close_retry_count,
    _increment_pre_close_retry_count,
    _mark_pre_close_completed,
    _pre_close_was_completed,
    _mark_morning_daily_completed,
    _morning_daily_was_completed,
    _mark_daily_signal_pending,
    _mark_daily_signal_completed,
    _daily_signal_is_pending,
    _daily_signal_was_completed,
    _mark_ai_daily_report_pending,
    _mark_ai_daily_report_sent,
    _ai_daily_report_was_sent,
    _ai_daily_report_is_pending,
    execute_run,
    execute_run_for_horus,
    execute_pending_entries,
    execute_pending_daily_entries_for_horus,
    _signal_auto_execution_enabled,
    _scheduler_signal_tickers,
    _record_direct_main_channel_signal_delivery,
    _publish_scheduler_signal_deliveries,
    _background_ops_paused_for_time_travel,
    _reconcile_scheduler_pre_close_previews,
    _scheduler_scan_type,
    _scheduler_run_key,
    _run_is_durable_completed,
    _completed_daily_signal_run_has_results,
    _env_float,
    _parse_scheduler_datetime,
    _scheduler_freshness,
    _daily_signal_history_ready,
    _pre_close_intraday_ready,
    _log_scheduler_data_waiting,
    _sync_scheduler_data,
    _daily_signal_run_date,
    _history_and_intraday_ready,
    _ensure_scheduler_data_ready,
    _persist_scheduler_signal_run,
    _scan_display_label,
    _should_send_no_signal_notice,
    _broadcast_no_signal_notice,
    scheduled_scan_logic,
    scheduled_intraday_scan,
    _pre_close_is_past_hard_deadline,
    _schedule_pre_close_retry,
    scheduled_pre_close_scan,
    scheduled_daily_signal_scan,
    scheduled_morning_daily_signal_scan,
    scheduled_daily_signal_pipeline,
    _build_ai_report_telegram_message,
    _ai_daily_report_run_date,
    _daily_ai_report_history_freshness,
    _daily_ai_report_history_is_ready,
    _log_ai_report_waiting_for_history,
    _ai_report_payload_has_stale_inputs,
    scheduled_daily_ai_report_dispatch,
    maybe_dispatch_pending_ai_daily_report_after_data_update,
    scheduled_weekly_analysis_report_dispatch,
    scheduled_monthly_analysis_report_dispatch,
    scheduled_managed_advisory_dispatch,
    scheduled_failed_delivery_retry,
    scheduled_weekly_walkforward_validation,
    scheduled_wfa_metrics_update,
    scheduled_system_audit,
    scheduled_daily_database_backup,
    scheduled_trade_monitor,
    scheduled_followup_processing,
    _scheduler_int_setting,
    get_market_signal_schedule,
    reschedule_market_jobs,
    catchup_morning_daily_signal,
    maybe_run_pending_daily_signal_after_data_update,
    maybe_run_pending_pre_close_signal_after_data_update,
    catchup_missed_post_market_jobs,
    EdgePipelineHandler,
    start_edge_pipeline_watcher,
    monitor_system_positions,
    check_exit_conditions,
    SystemMonitor,
    SignalExecutor,
)
