"""
ROUTES SYSTEM PACKAGE
=====================
System management, maintenance, telemetry, and security endpoints.
"""

from core.pipeline import refresh_pipeline_state, read_worker_state
from core.auth import get_api_key
from database import db
from routes.shared import (
    HARD_RESET_TOKENS,
    get_durable_provisioning_state,
    get_system_state_snapshot,
    is_stale_overridden,
    scheduler,
    set_stale_override,
)

from .maintenance import (
    confirm_holiday_logic,
    delete_holiday_logic,
    get_backfill_status_logic,
    get_hard_reset_token_logic,
    hard_reset_system_logic,
    list_holidays_logic,
    stale_override_toggle_logic,
    start_historical_backfill_logic,
    upsert_holidays_logic,
)
from .router import (
    confirm_holiday,
    confirm_operator_trading_plan,
    delete_holiday,
    get_audit_logs,
    get_backfill_status,
    get_boot_system_status,
    get_full_system_status,
    get_hard_reset_token,
    get_harvester_status,
    get_live_execution_guard,
    get_memory_diagnostics,
    get_operator_deviation_journal,
    get_operator_end_of_day_review,
    get_operator_trading_plan_status,
    get_system_integrity_report,
    get_system_status,
    hard_reset_system,
    list_holidays,
    public_router,
    record_operator_deviation,
    router,
    set_live_execution_guard,
    stale_override_toggle,
    start_harvester_service,
    start_historical_backfill,
    stop_harvester_service,
    upsert_holidays,
)
from .state import (
    _OPERATOR_DEVIATION_CATEGORIES,
    _build_boot_status_payload,
    _build_operator_lockout_summary,
    _day_bounds,
    _db_connection_available,
    _emit_operator_event,
    _latest_plan_confirmation,
    _manual_override_abuse_state,
    _parse_iso_date,
    _safe_json_load,
    _serialize_holiday,
    _serialize_live_execution_guard,
    _serialize_provisioning_state,
    _serialize_published_signal_lifecycle_summary,
    _serialize_signal_desk_summary,
    _serialize_signal_followup_summary,
    _serialize_telegram_config,
    _serialize_trading_plan_status,
    _signal_desk_lane_counts,
    _signal_desk_lane_key,
    _upsert_holiday,
    logger,
)
from .telemetry import (
    confirm_operator_trading_plan_logic,
    get_audit_logs_logic,
    get_boot_system_status_logic,
    get_full_system_status_logic,
    get_live_execution_guard_logic,
    get_memory_diagnostics_logic,
    get_operator_deviation_journal_logic,
    get_operator_end_of_day_review_logic,
    get_operator_trading_plan_status_logic,
    get_system_integrity_report_logic,
    get_system_status_logic,
    record_operator_deviation_logic,
    set_live_execution_guard_logic,
)

__all__ = [
    # Routers
    "router",
    "public_router",
    "logger",
    # Shared / Pipeline
    "refresh_pipeline_state",
    "read_worker_state",
    "get_api_key",
    "db",
    "HARD_RESET_TOKENS",
    "get_durable_provisioning_state",
    "get_system_state_snapshot",
    "is_stale_overridden",
    "scheduler",
    "set_stale_override",
    # State & Serialization
    "_OPERATOR_DEVIATION_CATEGORIES",
    "_serialize_provisioning_state",
    "_serialize_telegram_config",
    "_serialize_signal_desk_summary",
    "_signal_desk_lane_key",
    "_signal_desk_lane_counts",
    "_serialize_published_signal_lifecycle_summary",
    "_serialize_signal_followup_summary",
    "_safe_json_load",
    "_day_bounds",
    "_parse_iso_date",
    "_serialize_holiday",
    "_upsert_holiday",
    "_emit_operator_event",
    "_latest_plan_confirmation",
    "_manual_override_abuse_state",
    "_serialize_trading_plan_status",
    "_build_operator_lockout_summary",
    "_serialize_live_execution_guard",
    "_db_connection_available",
    "_build_boot_status_payload",
    # Endpoint Handlers
    "stale_override_toggle",
    "confirm_holiday",
    "list_holidays",
    "upsert_holidays",
    "delete_holiday",
    "get_system_status",
    "get_boot_system_status",
    "get_full_system_status",
    "get_memory_diagnostics",
    "get_live_execution_guard",
    "set_live_execution_guard",
    "get_operator_trading_plan_status",
    "confirm_operator_trading_plan",
    "record_operator_deviation",
    "get_operator_deviation_journal",
    "get_operator_end_of_day_review",
    "get_audit_logs",
    "get_system_integrity_report",
    "get_harvester_status",
    "start_harvester_service",
    "stop_harvester_service",
    "get_hard_reset_token",
    "hard_reset_system",
    "start_historical_backfill",
    "get_backfill_status",
    # Business Logics
    "stale_override_toggle_logic",
    "confirm_holiday_logic",
    "list_holidays_logic",
    "upsert_holidays_logic",
    "delete_holiday_logic",
    "get_system_status_logic",
    "get_boot_system_status_logic",
    "get_full_system_status_logic",
    "get_memory_diagnostics_logic",
    "get_live_execution_guard_logic",
    "set_live_execution_guard_logic",
    "get_operator_trading_plan_status_logic",
    "confirm_operator_trading_plan_logic",
    "record_operator_deviation_logic",
    "get_operator_deviation_journal_logic",
    "get_operator_end_of_day_review_logic",
    "get_audit_logs_logic",
    "get_system_integrity_report_logic",
    "get_hard_reset_token_logic",
    "hard_reset_system_logic",
    "start_historical_backfill_logic",
    "get_backfill_status_logic",
]
