"""
MARKET INDEX LISTS & METADATA
=============================
Loads market metadata (indices, sectors, names) from market_metadata.json.
Generated by update_market_metadata.py from DirectFN source files.
Thread-safe, mtime-cached in-memory representation.
"""

from core.settings import settings
from core.exclusions import EXCLUDED_TICKERS
import json
import os
import threading
import time
from typing import Any, Dict, Optional, Set

METADATA_FILE = settings.get_resource_path("market_metadata.json")

# Default structures
EGX_30: Set[str] = set()
EGX_70: Set[str] = set()
EGX_100: Set[str] = set()

SECTOR_MAP: Dict[str, str] = {}  # Ticker -> Sector Name
NAME_MAP: Dict[str, str] = {}    # Ticker -> Company Name

_METADATA_LOCK = threading.RLock()
_METADATA_MTIME: float = -1.0
_MARKET_LIST_CACHE: Dict[str, Set[str]] = {}
_CACHE_STATS: Dict[str, Any] = {
    "hits": 0,
    "misses": 0,
    "reloads": 0,
    "last_loaded": None,
}


def load_metadata(force: bool = False) -> bool:
    """
    Loads market metadata from METADATA_FILE if the file changed or force=True.
    Thread-safe and fast: avoids repeated disk I/O and JSON deserialization.
    Returns True if reloaded from disk, False if served from cache.
    """
    global _METADATA_MTIME
    with _METADATA_LOCK:
        if not os.path.exists(METADATA_FILE):
            _CACHE_STATS["misses"] += 1
            return False

        try:
            current_mtime = os.path.getmtime(METADATA_FILE)
        except OSError:
            current_mtime = -1.0

        if not force and _METADATA_MTIME > 0 and current_mtime == _METADATA_MTIME and bool(EGX_30 or EGX_70 or EGX_100):
            _CACHE_STATS["hits"] += 1
            return False

        # 1. Reset current metadata to prevent cross-market bleeding
        EGX_30.clear()
        EGX_70.clear()
        EGX_100.clear()
        SECTOR_MAP.clear()
        NAME_MAP.clear()
        _MARKET_LIST_CACHE.clear()

        # 2. Load from the globally defined METADATA_FILE
        try:
            with open(METADATA_FILE, 'r', encoding='utf-8') as f:
                data = json.load(f)

            indices = data.get("indices", {})
            EGX_30.update(indices.get("EGX30", []))
            EGX_70.update(indices.get("EGX70", []))
            EGX_100.update(indices.get("EGX100", []))

            # For non-EGX markets, they might use 'MAIN' as index name
            if not EGX_30 and indices.get("MAIN"):
                EGX_30.update(indices.get("MAIN", []))

            SECTOR_MAP.update(data.get("sectors", {}))
            NAME_MAP.update(data.get("names", {}))

            # Ensure EGX100 contains all if not explicit
            if not EGX_100:
                EGX_100.update(EGX_30)
                EGX_100.update(EGX_70)

            _METADATA_MTIME = current_mtime
            _CACHE_STATS["reloads"] += 1
            _CACHE_STATS["last_loaded"] = time.time()
            return True

        except Exception as e:
            print(f"Error loading market metadata: {e}")
            return False


# Load on module import
load_metadata()


def invalidate_cache() -> None:
    """Forces the universe cache to be purged and reloaded on next access."""
    global _METADATA_MTIME
    with _METADATA_LOCK:
        _METADATA_MTIME = -1.0
        _MARKET_LIST_CACHE.clear()


def get_universe_cache_stats() -> Dict[str, Any]:
    """Returns telemetry on universe metadata cache hits, reloads, and symbol counts."""
    with _METADATA_LOCK:
        return {
            "hits": _CACHE_STATS["hits"],
            "misses": _CACHE_STATS["misses"],
            "reloads": _CACHE_STATS["reloads"],
            "last_loaded": _CACHE_STATS["last_loaded"],
            "mtime": _METADATA_MTIME,
            "egx30_count": len(EGX_30),
            "egx70_count": len(EGX_70),
            "egx100_count": len(EGX_100),
            "sector_count": len(SECTOR_MAP),
            "name_count": len(NAME_MAP),
        }


def get_market_list(choice: str) -> Set[str]:
    """
    Returns the set of tickers for the given choice.
    Options: '30', '70', '100', 'ALL'
    Thread-safe and cached. Returns a copy so callers cannot mutate the cache.
    """
    choice = str(choice).upper().strip()
    normalized_key = (
        "30" if choice in ("30", "EGX30") else (
            "70" if choice in ("70", "EGX70") else (
                "100" if choice in ("100", "EGX100") else "ALL"
            )
        )
    )

    with _METADATA_LOCK:
        if normalized_key in _MARKET_LIST_CACHE:
            return _MARKET_LIST_CACHE[normalized_key].copy()

        if normalized_key == "30":
            res = EGX_30 - EXCLUDED_TICKERS
        elif normalized_key == "70":
            res = EGX_70 - EXCLUDED_TICKERS
        elif normalized_key == "100":
            res = EGX_100 - EXCLUDED_TICKERS
        else:
            all_tickers = set()
            all_tickers.update(EGX_30)
            all_tickers.update(EGX_70)
            all_tickers.update(EGX_100)
            all_tickers.update(SECTOR_MAP.keys())
            all_tickers.update(NAME_MAP.keys())
            res = all_tickers - EXCLUDED_TICKERS

        _MARKET_LIST_CACHE[normalized_key] = res
        return res.copy()


def get_sector(ticker: str) -> str:
    with _METADATA_LOCK:
        t = str(ticker).upper().strip()
        return SECTOR_MAP.get(t, SECTOR_MAP.get(ticker, "Unknown"))


def get_company_name(ticker: str) -> str:
    with _METADATA_LOCK:
        t = str(ticker).upper().strip()
        return NAME_MAP.get(t, NAME_MAP.get(ticker, ticker))


def is_egx30_ticker(ticker: str) -> bool:
    """Return whether a ticker belongs to the EGX30 basket."""
    with _METADATA_LOCK:
        t = str(ticker).upper().strip()
        return t in EGX_30 or ticker in EGX_30


def is_egx70_ticker(ticker: str) -> bool:
    """Return whether a ticker belongs to the EGX70 basket."""
    with _METADATA_LOCK:
        t = str(ticker).upper().strip()
        return t in EGX_70 or ticker in EGX_70

